### ISSUE TITLE
Keyboard lag on Mac OS? 

### ISSUE THREAD

**Issue by yeume** [tompi/cheapino#100]
Has anyone faced keyboard input lag while using the cheapino on a Mac OS (only at the login screen)? It works fine once I've logged in, but otherwise there is an input lag (have to hit a key (random) multiple times for it to register any sort of keystroke and I'm not sure if they're even correct because it always says the password is wrong. All of my other keyboards work just fine at the login screen (keebio iris, nico & steph arisu) except for the cheapino (v2) I built. 

I'm using a 2018 macbook pro on Sonoma 14.7

**Comment by tompi** [comment]
Hi. Im on macs exclusively, and havent noticed. Could you test with another cable(maybe cheaper)? Or if you Are running it through a docking station, try directly?

Not sure what this could be...

**Comment by yeume** [comment]
Sorry for the late update! With your suggestions for debugging, I've tried:

- Rebooting
- connecting a USB-c to usb-c cable directly to my macbook
- using a USB-A (plugged into an adapter for my macbook) to usb-c

Unfortunately, neither of these solved my issue.

**Comment by yeume** [comment]
Yep! The iris is qmk as well (uses via not vial though, not sure if that matters).

The led of the cheapino does the initial color loop when first plugged but stays green afterwards and does not change.

**Comment by yeume** [comment]
Just tried it on my kbdcraft Adam which also runs on vial but did not have any input lag so that debunks my suspicion. It's very strange, I'm not sure why it only behaves this way on the cantor remix and cheapino

**Comment by tompi** [comment]
Im wondering if this might be related to nkro somehow...
Could you test attached firmware for lag(its just a build stripped of nkro and some other suspects...)

[cheapino_tompi.uf2.zip](https://github.com/user-attachments/files/17821236/cheapino_tompi.uf2.zip)

**Comment by yeume** [comment]
the firmware you gave me seems to flash, but then never boots and is not recognized by my computer (tried unplugging and replugging the mcu after the flash). Also, now when the keyboard is connected, the mcu led color is now purple instead of green -- is this usually just random based on a flash?

**Comment by tompi** [comment]
Did you unzip it? Btw, you have version 2 of the cheap ion?

**Comment by yeume** [comment]
Yep! Unzipped, put the mcu into dfu, then dragged the uf2 file into the folder. And yes I'm on v2

**Comment by tompi** [comment]
Ooof, I probably messed up somehow... I tried again with attached firmware, tried to turn off some options.
Is it better?
[cheapino_vial.uf2.zip](https://github.com/user-attachments/files/17879491/cheapino_vial.uf2.zip)

**Comment by yeume** [comment]
Sorry for the late reply! I just haven't had the chance to flash the firmware, I will report back soon.

**Comment by yeume** [comment]
Just tried it again this morning, it works fantastically! What did you change? I want to try something similar on my cantor remix.

**Comment by tompi** [comment]
Hey, I turned off mouse keys and nkro and changed usb pid:

![image](https://github.com/user-attachments/assets/793160eb-6fed-4997-8539-113d90e8dda7)

**Comment by yeume** [comment]
Well I tinkered with the cantor and flashed the firmware but it still has the same issue. However it's definitely fixed for the cheapino. Thanks again!
