### ISSUE TITLE
V2 Case thin walls

### ISSUE THREAD

**Issue by ktowen** [tompi/cheapino#113]
I sent the case to jlc3dp.com to 3d print and they sent me an email after reviewing the files saying that some walls are too thin and could break during printing. I don't have any experience with 3d printing, is the risk acceptable or is this something that can be fixed?

This is the email they sent:

> the wall thickness of those indicated red area is too thin, which has high risks of loss, deformation ,crack, or damage during the printing process.
> 
> Could you please confirm if the risks are acceptable for you?
> 
> If not, could you please kindly increase it to be at least 0.8 mm to proceed? 1.5 mm will be better.Then we will activate the ' replace file' button for you.
> 
> ![image](https://github.com/user-attachments/assets/c314dcbf-84f1-43e5-bbd6-ec2a982302d0)

**Comment by glennmca-dev** [comment]
The walls are thin, but i've printed the case twice. Once on a badly calibrated ender 5 and once on a bambulab A1. It's been fine both times, Probably worth the risk

**Comment by tompi** [comment]
Several people have printed it, but yeah, the are thin. 

I hope you print using PLA?

I printed a few skeletyls at jlcpcb, and also got that warning then...

**Comment by ktowen** [comment]
Thank you all for the clarification. I set it to print in resin, let's see if that works well

**Comment by tompi** [comment]
Should be ok, but be very careful when you mount the melt inserts. Resin kind of degrades in stead of melting.

**Comment by schuay** [comment]
> Thank you all for the clarification. I set it to print in resin, let's see if that works well

@ktowen How did it turn out? I'm at the same step right now. 

FYI it's not possible to select PLA since the model is too small. "The minimum build size for PLA is 3.00x3.00x1.00cm, please change the material." Do you perhaps have other material suggestions?
