### ISSUE TITLE
Cheapino V2 build. Strange behaviour.

### ISSUE THREAD

**Issue by soul-wish** [tompi/cheapino#26]
Hi, @tompi.
I've finally soldered everything together but the keyboard works very strange. I can't get what is wrong with it, because this is my first custom build, so I don't have any experience in the process. But I've tried to do everything according to the build guide and in the correct order.
Unfortunately the left half is not working (not a single key). When I connect the right half then some of the keys on the right side are working, but the keycodes are VERY wrong.
I've tried to flash it by using my custom layout, and then tried to flesh it by using default one:

`qmk flash -kb cheapino -km default`

So, the left half is not registering any keypresses.

The right half prints the following (in order of the rows from left to right):
top row: nothing is printed (no keys working)
second row prints: `wesdx`
third row prints: `<tab>q<space>a`
thumbs row: `<nothing>cz`

Here are some photos of my build, maybe you will be able to find something wrong. 
![IMG_1154 Large](https://github.com/tompi/cheapino/assets/1968098/ef69bc6b-3f4c-482c-abee-4849781fe811)
![IMG_1155 Large](https://github.com/tompi/cheapino/assets/1968098/2e39983c-fc8b-4fbe-bee2-3c720531cd7e)
![IMG_1156 Large](https://github.com/tompi/cheapino/assets/1968098/16287ab3-ffce-4c51-94c8-7bc1b2368952)
![IMG_1157 Large](https://github.com/tompi/cheapino/assets/1968098/48c3ff86-f687-477f-829b-c997ab0cbf15)

Thanks for this awesome project, anyway.

**Comment by soul-wish** [comment]
It was just a misconfiguration in my local git branch ¯\_(ツ)_/¯

**Comment by tompi** [comment]
Nice build! Seems you solved your problem before I woke up:) send me a picture when you got it working with keycaps and all!
