### ISSUE TITLE
just a tip - GET A CRIMPER!

### ISSUE THREAD

**Issue by jinchoung** [tompi/cheapino#35]
just wanted to offer a tip that's made my experience much much smoother - get an ethernet cable crimper!
they just don't make them THIS short and this has really perfected my setup!

![IMG_0104](https://github.com/tompi/cheapino/assets/3815299/5306bcd7-c114-4edd-82be-12c387977412)

**Comment by tompi** [comment]
Thats a good tip! Ill incorporate this into the documentation. 

Ps. What keycaps Are those?

**Comment by jinchoung** [comment]
hey thomas,

cool! oh and the key caps are these
https://www.aliexpress.us/item/3256804695049488.html?spm=a2g0o.order_list.order_list_main.93.77261802nU0Wfq&gatewayAdapt=glo2usa
...

i was very nervous pulling the trigger on them cuz i didn't know whether
they would fit the switches but everything fit and works like a champ!

hope all is well with you and yours.

jin
