### ISSUE TITLE
Index and Middle finger columns stop working

### ISSUE THREAD

**Issue by BradyJ27** [tompi/cheapino#37]
Cheapino v1 btw.

Pretty consistently the two columns on the right board stop working for like 30 seconds or so. I've checked all of the solder points and I think they're all fine. I've also used both QMK and Vial, results are the same.

![PXL_20240516_200013509.jpg](https://github.com/tompi/cheapino/assets/26517764/7448e49c-2137-457d-a05d-35fd81120b9a)

![PXL_20240516_200028480.jpg](https://github.com/tompi/cheapino/assets/26517764/2d25e0f1-e391-43b0-957f-f7ec00b95451)

I've removed the keys that stop working. (Also, they all stop working and start again at the same time)

**Comment by tompi** [comment]
Hi. This sounds very annoying. Did you also check the soldering on the left part? Could you send a picture both sides of the left part also? These two columns both end up in one trace going through the rj45 socket ti the other side and into one pin of the mcu.

**Comment by BradyJ27** [comment]
Thanks for the quick response! 

I don't see anything wrong with the solder on the left, although it's not pretty I don't think it is causing issues. Attached are two pictures of the left side. 

![PXL_20240516_205016035.jpg](https://github.com/tompi/cheapino/assets/26517764/1ab18d5c-e2f7-4ee4-b346-37b38db1db64)

![PXL_20240516_205026028.jpg](https://github.com/tompi/cheapino/assets/26517764/565c7f08-2c07-450e-9102-709549ac4eea)

**Comment by tompi** [comment]
Looks pretty good. I agree. When this happens, is it related to the encoder? Does it help turning the encoder?

**Comment by tompi** [comment]
Ill dig out the schematics tomorrow and find the trace for this column. Typing from my bed and my wife is annoyed;)

**Comment by BradyJ27** [comment]
> Looks pretty good. I agree. When this happens, is it related to the encoder? Does it help turning the encoder?

As far as I know, no. It happens when I am just typing and not touching the encoder. I haven't tried to use the encoder to fix it, but I will try when it happens again.

No rush on resolving this, thanks again!

**Comment by tompi** [comment]
Hi again, I checked the layout for v1, and these two column are both mapped to column 1(with different diode directions per physical column).

Column 1 is routed through the square rj45 socket holes, so I would recommend you reflow these(especially the one on the right side seems a bit blobby, but hard to tell from pic: might be a cold joint).

The trace ends up at pin 4 on the mcu, counting from top left(marked 29). Try reflowing this as well, maybe add a little solder, seems a tad sparse maybe. 

Also, cant tell if you socketed the mcu, but if you did, it might be worth a try to gently pry it out, and check if leg at 29 is shorter than the others(ie was not pushed entirely in when soldered)

**Comment by BradyJ27** [comment]
Thanks so much! I've reflowed the square socket holes and the 29 pin. I don't _think_ the 29 leg is shorter, so I left it for now. I will try this if the issue keeps occurring. So far so good though!
