### ISSUE TITLE
Dead link on the ordering guide

### ISSUE THREAD

**Issue by eekhof** [tompi/cheapino#43]
Hello,

Thanks for the great design. I have been looking at the ordering guide (doc/orderingguide.md), and it seems the link to the silicone bumpers is dead (https://www.aliexpress.com/item/1005002619943801.html) . I am not entirely sure what they are supposed to look like and where exactly they are supposed to go below the PCB, which is why I wanted to ask if it would be possible to update the link to a similar model on AliExpress to make it easier to prevent a missbuy.

All the best

**Comment by eekhof** [comment]
My bad, I just saw that the link on the V1 guide is still active (https://www.aliexpress.com/item/1005003044229837.html), maybe it can be added to the buying guide.

**Comment by tompi** [comment]
Hi, thats very strange, both links works from my browser...

Is Ali Express filtering items from certain countries maybe? Where are you located?

Anyway, most bumpers should work fine, 5 or 6 mm wide, and 2mm thick are the most common I think.

**Comment by eekhof** [comment]
Oh, I am sorry, I should have validated this in a different browser/locale, thanks for the info.

I am located in Germany.
