### ISSUE TITLE
RJ45 socket is to far away from PCB edge

### ISSUE THREAD

**Issue by tompi** [tompi/cheapino#5]
A bit inconvenient when trying to unplug cable...

**Comment by azhizhinov** [comment]
Hello.
I've used another type RJ45 sockets.
You can find the more useful for your keyboard. 
[SEPOR-RJ45-SOCKET.kicad_mod.zip](https://github.com/tompi/cheapino/files/12111922/SEPOR-RJ45-SOCKET.kicad_mod.zip)
https://aliexpress.com/item/32974903992.html

**Comment by azhizhinov** [comment]
![IMG_20230217_073946](https://github.com/tompi/cheapino/assets/13044908/dd778a4f-5921-435b-a869-132e79b32c1a)

**Comment by tompi** [comment]
Fixed in 1355b80bf61a885dfb9796597a6b3016640277ef
