### ISSUE TITLE
QMK keyboard.json not found

### ISSUE THREAD

**Issue by paulomp90** [tompi/cheapino#54]
Hello, first of all thank you for your work on this project 👏 

I have a problem with `qmk`, I just checked out `qmk` repo. Then I followed the instructions, in the firmware guide (because I have a mac, I started on step 3) [here](https://github.com/tompi/cheapino/blob/master/doc/firmware.md#setting-up-and-compiling-qmk)

Unfortunately I am always getting the error `keyboard.json` not found.

Does anyone know what I am doing wrong?
Thanks in advance.

<img width="2065" alt="image" src="https://github.com/user-attachments/assets/d9731e74-29a7-4172-8c34-50fce6dab9e3">

**Comment by tompi** [comment]
Hi. Thats just a warning. The actual error is you Are missing a compiler. 

I think you should run qmk doctor and see what it says

**Comment by paulomp90** [comment]
@tompi thank you 👏  
I did not knew about the `doctor` command, some packages we're missing because of the checkout 😅

Now I need to finish soldering 😄  I will close the issue

**Comment by tompi** [comment]
Cool. Dont forget to send me a picture of the finished build! :)
