### ISSUE TITLE
[V1] K10 doesn't work

### ISSUE THREAD

**Issue by Clutchnp** [tompi/cheapino#55]
As stated in title my K10 key dosen't work, I have tried shorting the pins on switches and shorting the circuit before them but nothing happens while shorting either of them,tho if I short switch pin of k7 which is towards k10 with bottom diode pin of the diode between them , then k10 is pressed.
![2024-08-05-22-51-11-612](https://github.com/user-attachments/assets/97dfb6df-928f-44d6-88df-e329b394cde1)

What might be wrong?
Thanks for the good work!

**Comment by tompi** [comment]
Could be a diode is soldered in the wrong direction maybe? 

You have a pic of the other side?

**Comment by Clutchnp** [comment]
Mb found the error was a missing diode

Thanks for the hard work 😁
