### ISSUE TITLE
some key orders when pressed fast would activate unpressed keys 

### ISSUE THREAD

**Issue by Clutchnp** [tompi/cheapino#56]
For eg:- 
If I press 'ser' fast enough it would write as 'serf' and if i write 'esa' fast enough I will get 'esqa'

For reference: I am using qmk with Arch Linux 

you can see my config [here](https://github.com/Clutchnp/cheapino_qmk)

Ask me if you need anything else 

Thanks for the Hard work!!

**Comment by tompi** [comment]
- Hey! Did you customize the qmk code? I have some code to avoid ghosting, snd I think specifically those combnations Are part of it... does it happen if you Flash my example firmware?

Checkout the qmk fork mentioned in the firmware guide, there is some code there to avoid this I think

**Comment by Clutchnp** [comment]
I used the same firmware mentioned in the firmware.md guide and customized the keymaps.
Also using your keymap this still happens , for eg if I type 'rfp' it will type 'rfpt'

I am using cheapino v1 btw

Just to be sure I followed this firmware.md guide 
 https://github.com/tompi/cheapino/blob/master/doc/firmware.md and created my own keymap after that which was linked above

**Comment by tompi** [comment]
Okay, i assumed you were using v2.  I will make an attempt to backport a fw fix for this for v1 during the weekend.

**Comment by tompi** [comment]
Hey, sorry for the delay, could you check if this fixes your problem: https://github.com/tompi/qmk_firmware/commit/bad9c6d3639c779faf75e22ab21cb0a0988282e3

If so I will update the vial fw and the v1 releases

**Comment by Clutchnp** [comment]
Yes this fixes it thank you very much
