### ISSUE TITLE
Encoder button always on

### ISSUE THREAD

**Issue by ihales** [tompi/cheapino#60]
Thanks for sharing such a cool project! I built my first last night and loved it.

I've ended up with one problem- appears that the encoder button is always depressed, even when the right and left halves aren't even connected.

When I connect the two sides, none of the encoder interactions register.

I don't see any obvious problems, and I'm not sure the best way to troubleshoot. I'd love any pointers.

Here are photos of the front and back of the left board.

![image](https://github.com/user-attachments/assets/96d22cad-5f7a-42e3-b4d5-ee462e58643c)

![image](https://github.com/user-attachments/assets/290be20b-2431-43c8-8f9f-0aca219a2055)

![image](https://github.com/user-attachments/assets/bfd4223f-d3d7-464c-8f81-aefc066739d0)

**Comment by tompi** [comment]
Hi! Dont know which firmware you are using, but I would suggest trying the vial fw, without right half connected.
If you go to the test section there, is the encoder indicating press?

The pins on the mcu seems like they are not solidly connected to the hole? Maybee too little heat, or no flux? But that should not cause the encoder issue anyway...

P.S. Im a bit baffled by the bumper placement, are yours lower than your hotswap socket height?

**Comment by ihales** [comment]
Thanks so much for the response. Using the vial fw with only the left side connected, this is what I get:
<img width="752" alt="image" src="https://github.com/user-attachments/assets/1494eb32-4d2c-4ef5-9e9e-8377558d7fdc">

Thanks for the feedback on the MCU soldering - this is my first real soldering project so the suggestions are super helpful! While working on it, I did accidentally bridge one of the pins to the big encoder hole (on the left, if you're looking at the bottom), but I think I got that cleaned up.

And yeah, with the bumper placement, I put a first round directly on the PCB, but then there were a couple of places where it wasn't high enough, so I tried putting bumpers on the hot-swap sockets. I imagine it'll probably stress the sockets, so probably not ideal. I might try to print a case to help out.

Anyway, if nothing comes to mind, no worries. I have parts for another and I'll just give it another shot!

**Comment by tompi** [comment]
Ok, seems like you socketed the mcu?
Worth a try to take it out carefully, and then plug in usbc cable in the rp2040-zero, and see if you get the the same result in vial.

If you do, there is something wrong on the rp2040, either your soldering, or the mcu itself. You can then try with your other mcu, should work...

If it doesnt happen, should be something on the pcb.

If you have a multimeter, you could check that there is NOT continuity between any pins on the mcu socket...

**Comment by ihales** [comment]
I tried taking the MCU out and several pins came undone (the sketchy soldering you mentioned, so doubt). The MCU alone was fine and the sockets checked out. I just put it back together and resoldered the MCU and it started working!

Thanks for the suggestions and help. Here's a picture of the finished product!

![image](https://github.com/user-attachments/assets/bc75ac8f-1ff1-42a1-9b82-362a34a41c33)

**Comment by tompi** [comment]
Great! 

Looks really good with those keycaps. 

Good luck with the typing, now the hard part begins;)
