### ISSUE TITLE
not a git repository

### ISSUE THREAD

**Issue by CannonFodderSE** [tompi/cheapino#62]
Greetings,
Trying to  follow the instruction at tompi/cheapino [Setting up and compiling qmk](https://github.com/tompi/cheapino/blob/master/doc/firmware.md#setting-up-and-compiling-qmk) and I get the error below.  Looks like the source is gone.

`$ git remote add tompi https://github.com/tompi/qmk_firmware
fatal: not a git repository (or any of the parent directories): .git
`

Any suggestions?

Thanks,
Randy

**Comment by tompi** [comment]
Hey, I think you either skipped step 1-2 or failed to go into the qmk_firmware folder that should be there after step 2?

**Comment by tompi** [comment]
Hey @CannonFodderSE , did you figure out what was missing?

**Comment by CannonFodderSE** [comment]
Yes, I was running it from the wrong directory.
