### ISSUE TITLE
QMK generates weird layout

### ISSUE THREAD

**Issue by os-mey** [tompi/cheapino#63]
First of all, thank you so much for all your work!

I believe I assembled the keyboard correctly as it works perfectly with Vial. But I can't get any layout to work with qmk.

I followed the [firmware guide](https://github.com/tompi/cheapino/blob/master/doc/firmware.md) on a mac. I installed qmk using `python3 -m pip install qmk` and some of it's dependencies manually.  
Running `qmk flash -kb cheapino -km default` seems to be working:
<details>
<summary>Output</summary>

        Ψ Compiling keymap with gmake -r -R -f builddefs/build_keyboard.mk -s flash KEYBOARD=cheapino KEYMAP=default KEYBOARD_FILESAFE=cheapino TARGET=cheapino_default INTERMEDIATE_OUTPUT=.build/obj_cheapino_default VERBOSE=false COLOR=true SILENT=false QMK_BIN="qmk"

        ⚠ cheapino: Build marker "keyboard.json" not found.
        Generating: .build/obj_cheapino_default/src/info_deps.d                                             [OK]
        ⚠ cheapino: Build marker "keyboard.json" not found.
        arm-none-eabi-gcc (GNU Arm Embedded Toolchain 10.3-2021.10) 10.3.1 20210824 (release)
        Copyright (C) 2020 Free Software Foundation, Inc.
        This is free software; see the source for copying conditions.  There is NO
        warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
        
        Generating: .build/obj_cheapino_default/src/config.h                                                [OK]
        Generating: .build/obj_cheapino_default/src/keymap.c                                                [OK]
        Generating: .build/obj_cheapino_default/src/info_config.h                                           [WARNINGS]
         |
         | ⚠ cheapino: Build marker "keyboard.json" not found.
         |
        Generating: .build/obj_cheapino_default/src/default_keyboard.c                                      [WARNINGS]
         |
         | ⚠ cheapino: Build marker "keyboard.json" not found.
         |
        Generating: .build/obj_cheapino_default/src/default_keyboard.h                                      [WARNINGS]
         |
         | ⚠ cheapino: Build marker "keyboard.json" not found.
         |
        Compiling: keyboards/cheapino/encoder.c                                                             [OK]
        Compiling: keyboards/cheapino/ghosting.c                                                            [OK]
        Compiling: keyboards/cheapino/matrix.c                                                              [OK]
        Compiling: keyboards/cheapino/cheapino.c                                                            [OK]
        Compiling: .build/obj_cheapino_default/src/default_keyboard.c                                       [OK]
        Compiling: quantum/keymap_introspection.c                                                           [OK]
        Compiling: quantum/quantum.c                                                                        [OK]
        Compiling: quantum/bitwise.c                                                                        [OK]
        Compiling: quantum/led.c                                                                            [OK]
        Compiling: quantum/action.c                                                                         [OK]
        Compiling: quantum/action_layer.c                                                                   [OK]
        Compiling: quantum/action_tapping.c                                                                 [OK]
        Compiling: quantum/action_util.c                                                                    [OK]
        Compiling: quantum/eeconfig.c                                                                       [OK]
        Compiling: quantum/keyboard.c                                                                       [OK]
        Compiling: quantum/keymap_common.c                                                                  [OK]
        Compiling: quantum/keycode_config.c                                                                 [OK]
        Compiling: quantum/sync_timer.c                                                                     [OK]
        Compiling: quantum/logging/debug.c                                                                  [OK]
        Compiling: quantum/logging/sendchar.c                                                               [OK]
        Compiling: quantum/logging/print.c                                                                  [OK]
        Compiling: quantum/matrix_common.c                                                                  [OK]
        Compiling: quantum/debounce/sym_defer_g.c                                                           [OK]
        Compiling: quantum/main.c                                                                           [OK]
        Compiling: lib/printf/src/printf/printf.c                                                           [OK]
        Compiling: drivers/eeprom/eeprom_driver.c                                                           [OK]
        Compiling: drivers/eeprom/eeprom_wear_leveling.c                                                    [OK]
        Compiling: quantum/wear_leveling/wear_leveling.c                                                    [OK]
        Compiling: platforms/chibios/drivers/wear_leveling/wear_leveling_rp2040_flash.c                     [OK]
        Compiling: quantum/color.c                                                                          [OK]
        Compiling: quantum/rgblight/rgblight.c                                                              [OK]
        Compiling: quantum/rgblight/rgblight_drivers.c                                                      [OK]
        Compiling: quantum/process_keycode/process_rgb.c                                                    [OK]
        Compiling: quantum/led_tables.c                                                                     [OK]
        Compiling: lib/fnv/qmk_fnv_type_validation.c                                                        [OK]
        Compiling: lib/fnv/hash_32a.c                                                                       [OK]
        Compiling: lib/fnv/hash_64a.c                                                                       [OK]
        Compiling: platforms/chibios/drivers/vendor/RP/RP2040/ws2812_vendor.c                               [OK]
        Compiling: quantum/bootmagic/bootmagic.c                                                            [OK]
        Compiling: quantum/process_keycode/process_caps_word.c                                              [OK]
        Compiling: quantum/caps_word.c                                                                      [OK]
        Compiling: quantum/deferred_exec.c                                                                  [OK]
        Compiling: quantum/process_keycode/process_grave_esc.c                                              [OK]
        Compiling: quantum/process_keycode/process_magic.c                                                  [OK]
        Compiling: quantum/mousekey.c                                                                       [OK]
        Compiling: quantum/send_string/send_string.c                                                        [OK]
        Compiling: quantum/process_keycode/process_space_cadet.c                                            [OK]
        Compiling: tmk_core/protocol/host.c                                                                 [OK]
        Compiling: tmk_core/protocol/report.c                                                               [OK]
        Compiling: tmk_core/protocol/usb_device_state.c                                                     [OK]
        Compiling: tmk_core/protocol/usb_util.c                                                             [OK]
        Compiling: platforms/suspend.c                                                                      [OK]
        Compiling: platforms/synchronization_util.c                                                         [OK]
        Compiling: platforms/timer.c                                                                        [OK]
        Compiling: platforms/chibios/hardware_id.c                                                          [OK]
        Compiling: platforms/chibios/platform.c                                                             [OK]
        Compiling: platforms/chibios/suspend.c                                                              [OK]
        Compiling: platforms/chibios/timer.c                                                                [OK]
        Compiling: platforms/chibios/bootloaders/rp2040.c                                                   [OK]
        Assembling: lib/chibios/os/common/startup/ARMCMx/compilers/GCC/crt0_v6m.S                           [OK]
        Assembling: lib/chibios/os/common/startup/ARMCMx/compilers/GCC/vectors.S                            [OK]
        Assembling: lib/chibios/os/common/ports/ARMv6-M-RP2/compilers/GCC/chcoreasm.S                       [OK]
        Compiling: tmk_core/protocol/chibios/usb_main.c                                                     [OK]
        Compiling: tmk_core/protocol/chibios/chibios.c                                                      [OK]
        Compiling: tmk_core/protocol/usb_descriptor.c                                                       [OK]
        Compiling: tmk_core/protocol/chibios/usb_driver.c                                                   [OK]
        Compiling: tmk_core/protocol/chibios/usb_endpoints.c                                                [OK]
        Compiling: tmk_core/protocol/chibios/usb_report_handling.c                                          [OK]
        Compiling: tmk_core/protocol/chibios/usb_util.c                                                     [OK]
        Compiling: lib/chibios/os/common/startup/ARMCMx/compilers/GCC/crt1.c                                [OK]
        Compiling: lib/chibios/os/rt/src/chsys.c                                                            [OK]
        Compiling: lib/chibios/os/rt/src/chrfcu.c                                                           [OK]
        Compiling: lib/chibios/os/rt/src/chdebug.c                                                          [OK]
        Compiling: lib/chibios/os/rt/src/chtrace.c                                                          [OK]
        Compiling: lib/chibios/os/rt/src/chvt.c                                                             [OK]
        Compiling: lib/chibios/os/rt/src/chschd.c                                                           [OK]
        Compiling: lib/chibios/os/rt/src/chinstances.c                                                      [OK]
        Compiling: lib/chibios/os/rt/src/chthreads.c                                                        [OK]
        Compiling: lib/chibios/os/rt/src/chtm.c                                                             [OK]
        Compiling: lib/chibios/os/rt/src/chstats.c                                                          [OK]
        Compiling: lib/chibios/os/rt/src/chregistry.c                                                       [OK]
        Compiling: lib/chibios/os/rt/src/chsem.c                                                            [OK]
        Compiling: lib/chibios/os/rt/src/chmtx.c                                                            [OK]
        Compiling: lib/chibios/os/rt/src/chcond.c                                                           [OK]
        Compiling: lib/chibios/os/rt/src/chevents.c                                                         [OK]
        Compiling: lib/chibios/os/rt/src/chmsg.c                                                            [OK]
        Compiling: lib/chibios/os/rt/src/chdynamic.c                                                        [OK]
        Compiling: lib/chibios/os/common/ports/ARMv6-M-RP2/chcore.c                                         [OK]
        Compiling: lib/chibios/os/hal/osal/rt-nil/osal.c                                                    [OK]
        Compiling: lib/chibios/os/oslib/src/chmboxes.c                                                      [OK]
        Compiling: lib/chibios/os/oslib/src/chmemcore.c                                                     [OK]
        Compiling: lib/chibios/os/oslib/src/chmemheaps.c                                                    [OK]
        Compiling: lib/chibios/os/oslib/src/chmempools.c                                                    [OK]
        Compiling: lib/chibios/os/oslib/src/chpipes.c                                                       [OK]
        Compiling: lib/chibios/os/oslib/src/chobjcaches.c                                                   [OK]
        Compiling: lib/chibios/os/oslib/src/chdelegates.c                                                   [OK]
        Compiling: lib/chibios/os/oslib/src/chfactory.c                                                     [OK]
        Compiling: lib/chibios/os/hal/src/hal.c                                                             [OK]
        Compiling: lib/chibios/os/hal/src/hal_st.c                                                          [OK]
        Compiling: lib/chibios/os/hal/src/hal_buffers.c                                                     [OK]
        Compiling: lib/chibios/os/hal/src/hal_queues.c                                                      [OK]
        Compiling: lib/chibios/os/hal/src/hal_flash.c                                                       [OK]
        Compiling: lib/chibios/os/hal/src/hal_mmcsd.c                                                       [OK]
        Compiling: lib/chibios/os/hal/src/hal_adc.c                                                         [OK]
        Compiling: lib/chibios/os/hal/src/hal_can.c                                                         [OK]
        Compiling: lib/chibios/os/hal/src/hal_crypto.c                                                      [OK]
        Compiling: lib/chibios/os/hal/src/hal_dac.c                                                         [OK]
        Compiling: lib/chibios/os/hal/src/hal_efl.c                                                         [OK]
        Compiling: lib/chibios/os/hal/src/hal_gpt.c                                                         [OK]
        Compiling: lib/chibios/os/hal/src/hal_i2c.c                                                         [OK]
        Compiling: lib/chibios/os/hal/src/hal_i2s.c                                                         [OK]
        Compiling: lib/chibios/os/hal/src/hal_icu.c                                                         [OK]
        Compiling: lib/chibios/os/hal/src/hal_mac.c                                                         [OK]
        Compiling: lib/chibios/os/hal/src/hal_mmc_spi.c                                                     [OK]
        Compiling: lib/chibios/os/hal/src/hal_pal.c                                                         [OK]
        Compiling: lib/chibios/os/hal/src/hal_pwm.c                                                         [OK]
        Compiling: lib/chibios/os/hal/src/hal_rtc.c                                                         [OK]
        Compiling: lib/chibios/os/hal/src/hal_sdc.c                                                         [OK]
        Compiling: lib/chibios/os/hal/src/hal_serial.c                                                      [OK]
        Compiling: lib/chibios/os/hal/src/hal_serial_usb.c                                                  [OK]
        Compiling: lib/chibios/os/hal/src/hal_sio.c                                                         [OK]
        Compiling: lib/chibios/os/hal/src/hal_spi.c                                                         [OK]
        Compiling: lib/chibios/os/hal/src/hal_trng.c                                                        [OK]
        Compiling: lib/chibios/os/hal/src/hal_uart.c                                                        [OK]
        Compiling: lib/chibios/os/hal/src/hal_usb.c                                                         [OK]
        Compiling: lib/chibios/os/hal/src/hal_wdg.c                                                         [OK]
        Compiling: lib/chibios/os/hal/src/hal_wspi.c                                                        [OK]
        Compiling: lib/chibios/os/hal/ports/common/ARMCMx/nvic.c                                            [OK]
        Compiling: lib/chibios/os/hal/ports/RP/RP2040/rp_isr.c                                              [OK]
        Compiling: lib/chibios/os/hal/ports/RP/RP2040/hal_lld.c                                             [OK]
        Compiling: lib/chibios/os/hal/ports/RP/LLD/DMAv1/rp_dma.c                                           [OK]
        Compiling: lib/chibios/os/hal/ports/RP/LLD/GPIOv1/hal_pal_lld.c                                     [OK]
        Compiling: lib/chibios/os/hal/ports/RP/LLD/SPIv1/hal_spi_lld.c                                      [OK]
        Compiling: lib/chibios/os/hal/ports/RP/LLD/TIMERv1/hal_st_lld.c                                     [OK]
        Compiling: lib/chibios/os/hal/ports/RP/LLD/UARTv1/hal_sio_lld.c                                     [OK]
        Compiling: lib/chibios/os/hal/ports/RP/LLD/RTCv1/hal_rtc_lld.c                                      [OK]
        Compiling: lib/chibios/os/hal/ports/RP/LLD/WDGv1/hal_wdg_lld.c                                      [OK]
        Compiling: lib/chibios-contrib/os/hal/ports/RP/LLD/I2Cv1/hal_i2c_lld.c                              [OK]
        Compiling: lib/chibios-contrib/os/hal/ports/RP/LLD/PWMv1/hal_pwm_lld.c                              [OK]
        Compiling: lib/chibios-contrib/os/hal/ports/RP/LLD/ADCv1/hal_adc_lld.c                              [OK]
        Compiling: lib/chibios-contrib/os/hal/ports/RP/LLD/USBDv1/hal_usb_lld.c                             [OK]
        Compiling: lib/chibios/os/hal/boards/RP_PICO_RP2040/board.c                                         [OK]
        Compiling: lib/chibios/os/hal/lib/streams/chprintf.c                                                [OK]
        Compiling: lib/chibios/os/hal/lib/streams/chscanf.c                                                 [OK]
        Compiling: lib/chibios/os/hal/lib/streams/memstreams.c                                              [OK]
        Compiling: lib/chibios/os/hal/lib/streams/nullstreams.c                                             [OK]
        Compiling: lib/chibios/os/hal/lib/streams/bufstreams.c                                              [OK]
        Compiling: lib/chibios/os/various/syscalls.c                                                        [OK]
        Compiling: platforms/chibios/syscall-fallbacks.c                                                    [OK]
        Compiling: platforms/chibios/wait.c                                                                 [OK]
        Compiling: platforms/chibios/synchronization_util.c                                                 [OK]
        Compiling: platforms/chibios/interrupt_handlers.c                                                   [OK]
        Compiling: lib/pico-sdk/src/rp2_common/hardware_clocks/clocks.c                                     [OK]
        Compiling: lib/pico-sdk/src/rp2_common/hardware_pll/pll.c                                           [OK]
        Compiling: lib/pico-sdk/src/rp2_common/hardware_pio/pio.c                                           [OK]
        Compiling: lib/pico-sdk/src/rp2_common/hardware_timer/timer.c                                       [OK]
        Compiling: lib/pico-sdk/src/rp2_common/hardware_flash/flash.c                                       [OK]
        Compiling: lib/pico-sdk/src/rp2_common/hardware_gpio/gpio.c                                         [OK]
        Compiling: lib/pico-sdk/src/rp2_common/hardware_claim/claim.c                                       [OK]
        Compiling: lib/pico-sdk/src/rp2_common/hardware_watchdog/watchdog.c                                 [OK]
        Compiling: lib/pico-sdk/src/rp2_common/hardware_xosc/xosc.c                                         [OK]
        Compiling: lib/pico-sdk/src/rp2_common/pico_bootrom/bootrom.c                                       [OK]
        Compiling: platforms/chibios/vendors/RP/stage2_bootloaders.c                                        [OK]
        Compiling: platforms/chibios/vendors/RP/pico_sdk_shims.c                                            [OK]
        Assembling: lib/pico-sdk/src/rp2_common/pico_divider/divider.S                                      [OK]
        Assembling: lib/pico-sdk/src/rp2_common/pico_int64_ops/pico_int64_ops_aeabi.S                       [OK]
        Linking: .build/cheapino_default.elf                                                                [OK]
        Creating binary load file for flashing: .build/cheapino_default.bin                                 [OK]
        Creating UF2 file for deployment: .build/cheapino_default.uf2                                       [OK]
        Copying cheapino_default.uf2 to qmk_firmware folder                                                 [OK]
        Creating load file for flashing: .build/cheapino_default.hex                                        [OK]
        
        Size after:
           text	   data	    bss	    dec	    hex	filename
              0	  37048	      0	  37048	   90b8	cheapino_default.uf2
        
        Flashing for bootloader: rp2040
        Waiting for drive to deploy...
        Flashing /Volumes/RPI-RP2 (RPI-RP2)
        Wrote 74240 bytes to /Volumes/RPI-RP2/NEW.UF2
</details>

I tried to use the default keyboard layout from cheapino on the qmk fork. But my layout seems to be something like this after flashing:

Layer0
```
|---|---|---|---|---|                   |---|---|---|---|---|
|   |   |   |   |   |                   |   |   |   |   |   |
|---|---|---|---|---|                   |---|---|---|---|---|
|   |   |   |   |   |                   | w | e | s | d | x |
|---|---|---|---|---|                   |---|---|---|---|---|
|   |   |   |   |   |                   |MO1| q |SPC| a |GUI|    (SPC --> space, GUI --> cmd key/KC_LGUI)
|---|---|---|---|---|---|---|   |---|---|---|---|---|---|---|
                |   |   |   |   |   | c | y |
                |---|---|---|   |---|---|---|
```
Turning encoder to the right: "fv"
Turning encoder to the left: "vf"
Pressing encoder: "r"

Layer1
```
|---|---|---|---|---|                   |---|---|---|---|---|
|   |   |   |   |   |                   |   |   |   |   |   |
|---|---|---|---|---|                   |---|---|---|---|---|
|   |   |   |   |   |                   | 2 | 3 |   |   |   |
|---|---|---|---|---|                   |---|---|---|---|---|
|   |   |   |   |   |                   |   | 1 |SPC|   |   |
|---|---|---|---|---|---|---|   |---|---|---|---|---|---|---|
                |   |   |   |   |   |   |   |
                |---|---|---|   |---|---|---|
```
Pressing encoder: "4"

I get similarly unexpected results with the other provided examples "lars" and "tompi" in "cheapino/keymaps/".  
Do you know what to do?

**Comment by tompi** [comment]
Hey! Are you sure picked the v2 branch? I suspect you Are compiling the v1
version…

***@***.***, 90786985

**Comment by os-mey** [comment]
Works like a charm, thank you so much!

**Comment by tompi** [comment]
Nice! Dont forget to send me a picture of the finished build ;)

**Comment by os-mey** [comment]
![20240905_154259](https://github.com/user-attachments/assets/68a1d57b-d7a9-4232-9b34-a684bf0a11a6)
Here is my built :)

**Comment by tompi** [comment]
Thank you. Looking great!
