### ISSUE TITLE
Question: Are the magnetic USB-C safe? 

### ISSUE THREAD

**Issue by Batres3** [tompi/cheapino#64]
I've read that magnetic USB-C is not compliant, and I've heard of a couple of people who have had issues. Has anyone here had any issues? If so are there any alternatives?

I'm specifically referring to non compliance with USB-C specifications as mentioned in this thread https://www.reddit.com/r/UsbCHardware/comments/motlhn/magnetic_usbc_cables_are_not_recommended/

**Comment by soul-wish** [comment]
I have two Cheapino V2s with magnetic connectors, and so far, I haven’t had any issues with them. So I'm not sure what you're referring to @Batres3

**Comment by Batres3** [comment]
@soul-wish sorry I wasn't very clear I updated the message

**Comment by tompi** [comment]
Did not have any issues... Was a guy at reddit which I suspected might have some bad magnetic usb-c cables(his board was heating up...), but he never replied back...)

Ive been using mine(branded "Elough") for years without issues, I love them!

Only time there was a problem was when a diode leg got stuck shorting the pads. Did not cause any damaged, just removed it...

**Comment by Batres3** [comment]
Ok! I think it should generally be ok to use magnetic cables with keyboards because of the extremely low power draw, still wanted to bring this up just so people know.

Also, thanks for adding the warning @tompi !
