### ISSUE TITLE
Possible to handwire?

### ISSUE THREAD

**Issue by ashok-arora** [tompi/cheapino#66]
Would to be possible to handwire the keeb, including the rj45 connector and the mcu connector?

**Comment by ashok-arora** [comment]
Oh okay, makes sense, thank you. 😄

**Comment by azzamsa** [comment]
> the rj45 connector needs to be attached to something, and there is also very little wiggle room in the case for loose wires.

@ashok-arora  Unless of course you take the Cheapino layout and make your own 3d case

**Comment by tompi** [comment]
@azzamsa  I would argue that at that point it is no longer a cheapino ;)

**Comment by azzamsa** [comment]
@ashok-arora there are many big Cheapino case that is suitable for hand-wire project.
Some thing like [this](https://www.printables.com/model/879047-two-case-designs-for-cheapinov2-split-ergo-keyboar). You can also type "cheapino" in the search bar, as there are many other cases.

<img src="https://github.com/user-attachments/assets/5494cb9e-dc5d-40fb-b3ab-0074c865819b" width="300" height="300"/>
