### ISSUE TITLE
choc support

### ISSUE THREAD

**Issue by waynehoover** [tompi/cheapino#7]
I like this board, but I prefer the low profile choc switches, any plans for adding choc support?

**Comment by tompi** [comment]
Sorry, Im not a big fan of chocs(big hands...).

This would require a separate PCB design, and chocs are so damn expensive they would ruin the whole concept ;)

**Comment by k3d3** [comment]
The main reason I'd be interested in a choc variant is because I have several choc switches laying around, and it would be great to put them to use cheaply.

I can totally get that redesigning the PCB would be a pain though.

**Comment by rprs** [comment]
(no need to reply, just +1'ing)

I respect your opinion, I just ask that you don't discard this idea completely. :)

Your layout has a better position for the thumb cluster compared to corne keyboards or the bastardkb dilemma. 

Maybe have the choc board in another repo ("Chocpino") to avoid tainting the design idea of affordability? Either way, thank you for creating the cheapino! :D
