### ISSUE TITLE
Parts list expanded

### ISSUE THREAD

**Issue by djdanielsson** [tompi/cheapino#71]
I was looking for some other options that are currently not listed in your parts list that I thought might be nice to add for people like me who want for example a clicky keyboard or different keycaps. I know you can't list them all but I thought a few other options might be nice. I am happy to PR something if anyone has some suggestions. I am currently looking to find some clicky switches if anyone has found any that work well.

**Comment by tompi** [comment]
Hey, sure, clickies are nice for home-office workers and sadists ;)

I have a cheapino with cherry blue switches which I really like, but my wife threatens to divorce me every time I use it...

Please add some more options in a pull request, Ill be happy to merge!

P.S. Im always on the lookout for nice blank keycaps, and also low profile mx, let me know if you come across some nice ones.

**Comment by djdanielsson** [comment]
Do you have a link to the cherry blue switches that you have?

**Comment by tompi** [comment]
Unfortunately no, harvested from old keyboard. But i assume they Are like any cherry blues...

**Comment by SadWitchBoards** [comment]
Honestly at this point I feel like we need a Cheapino fan page to share builds and shopping links. 🤣 As for clicky switches, I feel the cheaper Kailh box clicky switches or even the Gateron Melodic are good examples now.

**Comment by djdanielsson** [comment]
That's not a bad idea, maybe a Reddit thread for that which could be linked somewhere or similar.

**Comment by SadWitchBoards** [comment]
Maybe a subreddit with resources for budget ergo builds and a master list for Cheapino links?

**Comment by tompi** [comment]
Feel free to make a subreddit ;)

Closing this issue for now.
