### ISSUE TITLE
Issue with right side, missing all but 8 keys

### ISSUE THREAD

**Issue by frantathefranta** [tompi/cheapino#73]
Hey, I just attempted to make my first Cheapino but I'm struggling with making the right side work. This is where I am currently (the empty on the left is a bad hot swap connection, works with shorting manually):
<img width="878" alt="Screenshot 2024-09-21 at 9 55 19 PM" src="https://github.com/user-attachments/assets/70e92f8b-c8d6-4716-b874-c0c959611374">.
I read through other issues and it seems that my problem is either the Right side pad connection, MCU issues or the RJ45 socket. I've tried multiple RJ45 cables but they all do the same thing.  What issue is this most likely? Thanks for any help.

Pictures of my (very amateur soldering):

![IMG_9484](https://github.com/user-attachments/assets/caa35596-4bb6-49c3-96b1-b8bb7081b3c2)
![IMG_9486](https://github.com/user-attachments/assets/50cb683c-c730-4f0b-9fe7-efd22464374b)
![IMG_9488](https://github.com/user-attachments/assets/2ede650a-920a-4b2b-a394-9544bd8413ab)

**Comment by tompi** [comment]
Hey! This could very well be bad solder joints on one of the rj45 connectors or the mcu...

If you short 2 and 2 pins on the left rj45 connector, can you trigger all keys?

If so, reflow both rj45 ports. 
If not, reflow the right side pins of the mcu.

**Comment by frantathefranta** [comment]
I guess this is some sort of a progress. I've reflowed the RJ45 ports and that didn't make a difference. Then I re-did the MCU (both the top and bottom) and got this:
![Screenshot_20240922_112049](https://github.com/user-attachments/assets/eee36e9d-7fb3-43e3-b06e-3053af7d6c12)

More keys are registering but at the same time I've lost 4 (the knob now works fully though, previously it could only do the press). I guess I'll try again with the MCU.

**Comment by frantathefranta** [comment]
Played around more with the MCU and RJ45 ports and got all the keys working finally. Seems to work better when there are big blobs of solder (which I thought wasn't the right way). Sadly my knob encoder stopped working (press works, spin does not).

**Comment by tompi** [comment]
Hey. Encoder twist does not register in vial test page. Maybe they work in regular use? Page up/down is default i think. 

For one key: kan you triggger på shorting pads. If not, does it register if you bypass the diode? Might be bad diode or bad switch or loose hotswap socket

**Comment by tompi** [comment]
Also, checkout a soldering tutorial. I think you might be using too low temp or too little flux, but not sure.

**Comment by frantathefranta** [comment]
Looks like it was a bad diode connection. Now I'm fully functional. Also I got confused by the rotary encoder because it worked in the VIAL (by scrolling the tabs), then stopped, then worked again. Might have been something to do with my desktop setup. 
Anyway, many thanks for your assistance, I really appreciate it. Off to build a second keyboard.
