### ISSUE TITLE
Cheapino Mods/Variant

### ISSUE THREAD

**Issue by azzamsa** [tompi/cheapino#76]
Context:
- https://github.com/tompi/cheapino/issues/59
- https://github.com/tompi/cheapino/issues/57
- https://github.com/tompi/cheapino/issues/49
- https://github.com/tompi/cheapino/issues/7
- https://github.com/tompi/cheapino/issues/20
- https://github.com/tompi/cheapino/issues/70

My previous thoughts regarding mods/variants:
- https://github.com/tompi/cheapino/issues/74#issuecomment-2376054054
- https://github.com/tompi/cheapino/issues/74#issuecomment-2376059892

I’d suggest to use `wontfix` tags / in README.md to keep **Cheap**-ino focused on its original goal. You could provide the [ergogen](https://ergogen.xyz/) config for the Cheapino layout so others can easily add features like a 6th column, Choc support, LEDs, speakers, haptics, handwire, etc.
Here’s a reworded version:

Since we can easily modify the layout using the ergogen config, it also provides a `jscad` file for people to adjust the case, making it suitable for hand-wiring.

Of course, these would be forks, and they’re free to ask for comments or suggestions from you, @tompi, in their own repositories.

**Comment by tompi** [comment]
Started ung wontfix now.
