### ISSUE TITLE
Confused on starter keymap layout

### ISSUE THREAD

**Issue by cgregurich** [tompi/cheapino#81]
Just built my cheapino and the default layout/layers you have in the vial website (?) seems to be kind of wacky. Eg. no shift, ctrl, backspace, etc. I know that it's super customizable but because this is my first ergo keyboard, I'm not sure where to even begin so I need a good starting layout that more or less gets the job done "out of the box". Can anyone help me with this?

**Comment by tompi** [comment]
Yeah, didnt put much effort into the vial default keymapping... there is a miryoku firmware, which is kind of the goto standard...

Maybe Flash that and give it a go?

**Comment by cgregurich** [comment]
I'll try that, thanks for the quick reply :)

**Comment by tompi** [comment]
Closing, default keymap is mostly for testing. Ppl will eithe compile themselves or use vial or miryoku.
