### ISSUE TITLE
What to do on miroku qmk branch?

### ISSUE THREAD

**Issue by cgregurich** [tompi/cheapino#84]
In the firmware instruction it says:
> There is a branch of miryoku you can use for local builds here: https://github.com/tompi/qmk_firmware/tree/cheapinov2-miryoku

I checked out to this branch in the qmk repo but I'm not sure what to do after that. Where is the miryoku layout that I can flash??

**Comment by tompi** [comment]
Hey. I assume you are the guy i just chatted with on Reddit? ;)

https://www.reddit.com/r/ErgoMechKeyboards/s/eBRipAKZoZ
