### ISSUE TITLE
Two Rows On My Cheapino V2 Just Dont Work

### ISSUE THREAD

**Issue by skie3e** [tompi/cheapino#85]
the right half works perfectly but the two middle left rows on my left side dont work at all!

i've re-heated all hot-swap switches and diodes multiple times

would it you know which diode i could switch out to try and fix this?

![cheapino VIAL](https://github.com/user-attachments/assets/526e8e11-3dc8-47ee-8ff6-7a507057d0b3)
(i didnt plug in the right half but it works)

im using through hole diodes

i took the best photos i could, sorry they're so bad ;-;

![IMG_20241005_230108015_HDR](https://github.com/user-attachments/assets/7d763561-f2ce-4ca9-97f4-ec4ce211227f)
![IMG_20241005_230111270_HDR](https://github.com/user-attachments/assets/01fa4409-6f2a-4787-8bce-f84dcc49d415)
![IMG_20241005_230117417_HDR](https://github.com/user-attachments/assets/2ad616f7-2950-4e62-8cb5-294a030f2add)
![IMG_20241005_230122350_HDR](https://github.com/user-attachments/assets/87905191-4a2a-463a-94d4-c3230df41f4a)
![IMG_20241005_230024776_HDR](https://github.com/user-attachments/assets/c0296dbe-c5fb-481b-8b4d-6e219e0a0813)

ignore that some of my hot swap switches are melted, soldering is hard :P 

thanks in advance! i love this project!!!!

**Comment by tompi** [comment]
Hey, Im working on a visual debugging tool for this, ill give you a sneek peak :)

You should reflow the pin that I drew an arrow at, both columns go into that pin, so that has to be the culprit.
Also, try to use correct temp, flux, and time when soldering.

![image](https://github.com/user-attachments/assets/5df5cdd5-a59c-42b7-b4bd-acafedad56ab)

**Comment by skie3e** [comment]
wow did something weird happen, when i redid that i lost 4 keys on the right hand,, top row, outside moving in
also, now the left-most column triggers the middle column and the thumb cluster triggers the middle left column
not sure but i cant see any brigded connections, im so confused :P 

i currently ave no keyboard because my wire broke so im using on-screen keyboard 😭

**Comment by tompi** [comment]
Im afraid this very likely comes down to the soldering.
Take a look at this illustration, and maybe check out some youtube guides:
![image](https://github.com/user-attachments/assets/1fc0c169-896e-4dbe-b90d-d61bacbf67aa)

The image is from this guide:
https://www.circuitspecialists.com/blog/how-to-soldering-correctly-soldering-101/

**Comment by tompi** [comment]
Hey, just made a tool for this, check it out to debug:
https://tompi.github.io/cheapino/doc/troubleshooting/routing.html
