### ISSUE TITLE
Enable discussion

### ISSUE THREAD

**Issue by azzamsa** [tompi/cheapino#86]
Hi, @tompi 

I think you should enable discussion in this repo. As many issues is not a valid *issue*. It will start consuming your time eventually. 

Tell users to only open a valid issue (using the GitHub issue template such as checkboxes), and the rest goes to the discussion. Questions like these are not related to Cheapino and can be asked somewhere else (Discords, Reddits),  you can safely ignore them. If one of them happen to be a valid issue, you can convert it to an issue.

Best of luck!

**Comment by tompi** [comment]
sorry, not a big fan of the discussion feature of reddit ;)
