### ISSUE TITLE
Printable plate

### ISSUE THREAD

**Issue by bpingris** [tompi/cheapino#88]
Hello!
I am using my cheapino only with the PCB and rubber feet.

Are there any design available somewhere or a way to print/build a plate that I could attach under the pcb? 
That way I won't expose as much the components and I could attach some laptop support to add some tenting to the keyboard.

I can't print a "full" case as I have already soldered my switches to the pcb (I am not using hotswap sockets).

fwiw when I look at the [plate on the repository](https://github.com/tompi/cheapino/blob/master/case/plate.scad) I'd need to have some cuts so I could screw some M2 spacers to hold the plate to the pcb, whereas here it seems the the plate is completely filled
<img width="716" alt="image" src="https://github.com/user-attachments/assets/e3017506-82a9-49df-b016-7e60ebed2562">

Hope I'm clear enough!

**Comment by tompi** [comment]
Check the bottom-stls here: https://www.thingiverse.com/thing:6661648/files

You might need to use screws (m2) to fasten it, or maybe just glue it...(I think it should sit pretty ok as is, but might fall off...)

You can fasten magsafe stickers on these and then attach them to e.g. magsafe phone holders for max tenting flexibility.

**Comment by tompi** [comment]
The plate you linked to is just a helper for making the final case... 
Check out eg thi instead: https://github.com/tompi/cheapino/blob/master/case/cheapino-bottom-left.scad

left and right are different...

**Comment by bpingris** [comment]
awesome! thanks will check with the first link you provided
I tried to display the `bottom-left.scad` but I didn't quite understand what it was supposed to be
<img width="798" alt="image" src="https://github.com/user-attachments/assets/4883f38e-eb9e-4f59-9637-6a135ba92dc1">
as the render was quite ""_blurry_"", but now that you linked the first case I guess this is supposed to be this
<img width="546" alt="image" src="https://github.com/user-attachments/assets/c24896d8-2c04-4bfd-8b29-96597b85723b">

**Comment by tompi** [comment]
Sure, first render is blurry. Hit F6 for render and it should be fine
