### ISSUE TITLE
Can't enter dfu mode

### ISSUE THREAD

**Issue by zumosik** [tompi/cheapino#93]
Maybe I am just too stupid, but i can't enter dfu mode at all. 
Yesterday i entered it and dropped uf2 file, today doing same thing (holding boot while plugging usb-c) my controller just wont turn on and no drives appear. If I am just plugging usb-c keyboard works without problem. 

How to enter dfu?

**Comment by tompi** [comment]
Hey, the easiest way is probably with keyboad plugged in, hold down boot button, and press "reset".

Which should be the same as plugging in while holding boot, but easier to accomplish;)

If it doesnt work, maybe try another cable or even another computer?
